name: DonationBossbar
version: ${project.version}
main: fr.thefox580.donationbossbar.DonationBossBarPlugin
api-version: 1.21
authors: [ awesomepandapig, MarcusSlover, TheFox580 ]
commands:
  donationbb:
    description: Donation Bossbar Menu
