name: DonationBossbar
version: ${project.version}
main: me.awesomepandapig.donationbossbar.DonationBossBarPlugin
api-version: 1.19
authors: [ awesomepandapig, MarcusSlover ]
commands:
  donationbb:
    description: Donation Bossbar Menu